<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1345" started-at="2019-01-20T13:35:30Z" finished-at="2019-01-20T13:35:31Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1345" started-at="2019-01-20T13:35:30Z" finished-at="2019-01-20T13:35:31Z">
      <class name="c_parsingjson_JSONPATH.ParsingJson">
        <test-method status="FAIL" signature="parsingJsonFirstTest()[pri:0, instance:c_parsingjson_JSONPATH.ParsingJson@feb3fa]" name="parsingJsonFirstTest" duration-ms="1220" started-at="2019-01-20T13:35:30Z" finished-at="2019-01-20T13:35:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Stavan First Assert Failed expected [0001] but found [sdfaf]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Stavan First Assert Failed expected [0001] but found [sdfaf]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at c_parsingjson_JSONPATH.ParsingJson.parsingJsonFirstTest(ParsingJson.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parsingJsonFirstTest -->
        <test-method status="PASS" signature="parsingJsonSecondTest()[pri:0, instance:c_parsingjson_JSONPATH.ParsingJson@feb3fa]" name="parsingJsonSecondTest" duration-ms="38" started-at="2019-01-20T13:35:31Z" finished-at="2019-01-20T13:35:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parsingJsonSecondTest -->
        <test-method status="PASS" signature="parsingJsonThirdTest()[pri:0, instance:c_parsingjson_JSONPATH.ParsingJson@feb3fa]" name="parsingJsonThirdTest" duration-ms="16" started-at="2019-01-20T13:35:31Z" finished-at="2019-01-20T13:35:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- parsingJsonThirdTest -->
      </class> <!-- c_parsingjson_JSONPATH.ParsingJson -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
